# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f01bd738-4096-459d-8e35-83160ec4e6d3";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."root-enc".device = "/dev/disk/by-uuid/43f3066d-fa8a-4ef3-a9e6-54da9f30b63e";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3FB7-06B4";
      fsType = "vfat";
    };

  fileSystems."/mnt/hdd1" =
    { device = "/dev/disk/by-uuid/a7bb31e2-6a57-4857-bcfa-ac936312b1b9";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."hdd1-enc".device = "/dev/disk/by-uuid/dc507908-433b-4e58-8ba3-f3fd6e90cd48";

  fileSystems."/mnt/hdd0" =
    { device = "/dev/disk/by-uuid/63912162-7dc5-4ce7-92e7-5859bba9b9e9";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."hdd0-enc".device = "/dev/disk/by-uuid/e637c1b4-cbce-4b03-9708-79ff43024cc0";

  fileSystems."/mnt/hyperspeed" =
    { device = "/dev/disk/by-uuid/102e4512-9f47-49a2-a1dc-639a703a754b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."hyperspeed-enc".device = "/dev/disk/by-uuid/290f754c-d0a1-41a0-bf8d-75753692c238";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/10bd7af8-55a4-4956-8846-1c5d93330014"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp42s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
