forgejo:
    LFS_JWT_SECRET: ENC[AES256_GCM,data:N5gVhILbIAE0i6uUqQtqu5ES83sRIZNTBM0j+QsUatKZB7VkFuKqlHLmuw==,iv:svixJ/zGU2yZU+S+6XfHd6h3bjKeeXzSEjFu6EjE2RI=,tag:Arruj7gH6qGZjDt/vwLwkA==,type:str]
    database_password: ENC[AES256_GCM,data:SWHr7NA=,iv:0W5l1gfis07X/ewSJhvySNOxchiyHI/6aLMDdPivQfU=,tag:e8PEHI3KfS3c8oFhovnYhQ==,type:str]
    mailer:
        PASSWD: ENC[AES256_GCM,data:vV8MciKXUuIskxuz5FgU9xcj2QM=,iv:mwvFvgV6nmZO61jpIcfjpCl2vozT2DM/cKDddxW6HA8=,tag:sE3M9lmQyH2kH5LPUFa9qA==,type:str]
    security:
        INTERNAL_TOKEN: ENC[AES256_GCM,data:+A4U+rIWbVU9yi3d027+YrGr4dllzI/KGDJpOgfoDCI6VPI3ucp3pglcefjPXCBNyFECtEyCNAdQnTqAEsEVwsGIv85KHTj53N/LO8iNwBPlVA71rQxgNfK9BN7MFO9jIviqQo0hT/Yq,iv:x9DRAKkRH1eqDnMN+hyf2K8YKUHa1ILB7IEyhnv+Zuc=,tag:sstCI1wD+yl6VDncJzfIVw==,type:str]
    metrics:
        TOKEN: ENC[AES256_GCM,data:6Pi67rJxDmTe7ii2EcZD8CQFbGXh5C7uJxZJmlXNRVleAZsfSqOvOIIvhXBxNUj76GE2qp0SftDnK0AqrNHZFQ==,iv:mWgFmffGj+EgOYOOZzbxU/o84U8ZkyQHzfHdaZIEtlw=,tag:m5/mwlxJ9lhZDaBOQrw5cQ==,type:str]
    oauth2:
        JWT_SECRET: ENC[AES256_GCM,data:NgPNaf0RAlftHi8nLD+WyGRXLmg6LK6JexF5eDshUI3a1nRWfozbULuljA==,iv:JJ8XXGzG4m2Juhzb2KCMEv7uWFg6ohY60OXGOK9NFKo=,tag:cDqTu8TW8zIb8eaVwf1sBw==,type:str]
copyparty:
    passwords:
        ixhby: ENC[AES256_GCM,data:jY0AEpI5dcasg9EodiDxo0FMNKM7klx+GYuyGT/NYjNM5fLxFUlk1ApXGTRAU7OPxoXL1uGl9lL8zWzEp0ZwBw==,iv:zhwSJIcpjf/l9Hcn+r1yq15w2r/RWbgmerXeNwZysB0=,tag:++tpvmZZrYv3VGc7T8vC+g==,type:str]
        katie: ENC[AES256_GCM,data:oaZLKAauINz+cIfrYFPA0M9FgFbxLm34H45mgGGdhpEIcC39khLVBCh/tQZEAHT5ulacKbdr12tB3DQvCD/sHg==,iv:pmcKcKYtxOcfPWQRiv/gUpoHZzFVwNsqyO1rDbvUP7A=,tag:vaEaqa7GQ6eAWxwJY7KHcw==,type:str]
kanidm:
    oauth2:
        forgejo:
            secret: ENC[AES256_GCM,data:rfyaXFBv33B1ZOE0gmGfegqNh9CuJWLuNtoWZIBZm7I2IuPW75uSXbPIjC2QxvBwNbOhvrBz6THJ6XNfO1DtQw==,iv:PoyNo7BLYcKA1rCA/5nj8Svi8r25JxaazVhk6iqlCIw=,tag:f6kmESTESxaiXMb0kB97FQ==,type:str]
        grafana:
            secret: ENC[AES256_GCM,data:DYuhfGClH0cZLysHSl111n2XV+hL9f7ZqlFH/d4kGsND5AI/2+qxVnvo9WxHgUuh7EdcHe4DuiSDPip3ht74pQ==,iv:jWN8rRugCyLoEIZMjBl7l2JJR191SAPveMtl6oEHKys=,tag:Czkur7IrBuX2/Yk9Sa3KgQ==,type:str]
vm:
    auth: ENC[AES256_GCM,data:kD/n3KpTjbVhA/Xh6wYbFPoFolHuw9fnugVtHO1XzX/QqFWNogmZW3RcgnP7juqAd1RCa0BIriJndZTO2GLCzjnZB6ERDb3UVCm9DhQ2F6n6khyX/RuZD/FT6TK3+alS9GHIA71bgPDxL2T/6rgqkrrWcfNsHGfZFM8wSz/SibI=,iv:RAQ85LTWfoDTFdIuDyTelI6ZSNxG7H7/wiscvG4Ysyk=,tag:ui2vJtTTxcLaspq0LXXcAw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRT2syejZuRVVwWHdhNzk0
            Z1VGOXBiSmFGNEN0b0pIWHF5Y1ZZTkF0VWxnCjV0blJvbGxKSDAxdkx0c2FFT3NZ
            Mm5SRnAwb3VTMzh1SlcrT2dSM1psWUEKLS0tICtab3Bha0hyekxRVG0rNnlsK3dF
            Y0REN2l6VXc1Y1NQZUFDUnl4eXpIQjAKoTv2qqb0Y4n32/09UkgwkPM2oNVKxt3v
            SFz9zP60WLA33+R0/V58URv2iFoitEGs5jFngF4SGlq+fEIdiQFBtQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w7ncwyp6u9u3fu98zgrxxde7xtl7qzw7vxgudfdlemsh7eldtfcsm5gg4f
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSG0zUEMzTjVnMWJuNGVn
            Kzl4eDMvcStaODY1QkFHbTNKQjdrcnVPd3lrClJqZXp6TGRLd2lqUjYzQUd6WE5C
            ZW5jby9Gd1dtL3IvalVPaVdUWVYzV0kKLS0tIGQzMktEVForMFpWZ1IrZHgwM2tI
            SWJnZmFFY3lpRWNzQVZUNkt6VXR1UDAKD3myBvoIkAN3wb80IFLedr0n57E/tsGf
            m7ZuaXSNc+E1Uv68St7NycwM07n488eyM59FNhlH77Tucp5QL1UtVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1csqeanwl85a8fux7xvfcu2muv3f5kl9l0pjpvhl3ed97cep0aygsy5r6y6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNjlreUE5a3lKYUFMYUhp
            bTBGcEc0V3c0QUVpemh3cWdML1p6eEw3WFJZCllOVTd6dy8rK0UwQkN3d3g4bkh0
            eTJZNkR3amsyY1UvUFlaSlo4NlZjbjQKLS0tIDU5SE9vOG1USld3aDFsRzYxVTRH
            VlE4T2JoMytEdHBPaFJLam4vaG9KbjgK6s3354rAujSqjm8cXELRI19sOrFwo4De
            dh3wX5HE/OEB+FtevSv7bf9OMgwW/yFGPRe6gkAE+4PvF+J0GgJNDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gdwxehs50jd283eqz5kdh6q7w07hx4zsj0kx9m2kd9g5ul8pap5qfhx02w
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdEhqNklOQ2U4V3NFdGtL
            V0RIR0d4Q1FKcTNlSzNzU0t6YWRtMHNSRzM0CldKR1FkbGNVd0ovS003WS9YRUto
            VG9YUi9uK0VsYlg1WFZ0SGw5R2dHOEUKLS0tIDI1T0RDT1crdENJRy84dUh1UUFm
            SE0weWdlM1FFeG5sV1JvTW53aTcwNkUKNsgXdyTozoWUFjWVxfwSAYs+eopi1JTa
            Iua+n0/0QREin5JukfBBoXQVJRF3Yg1Jy6lXkraGboZVxwisRbA83A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14j4utewnafy533m86n0tfslsn7q43j9ksvfqq6yxkttj2j4wp5zs3sekv0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNGVvaXNhUjNFK0NCNTdO
            YTJDUXkyMTNDZW5xRE84TWVKbVF4d3VvVVJRCmRsamlMcDRlSEYwOHl6RnFlMHRG
            ZXVjS2x4UHA5YjNrNlZxMDNObUNOL2MKLS0tIFpRQ2JFM2JkWTZPc1E3ZkpNbHVF
            SXdrVUpoaENKbTFTOUIrQmY1eFNIcUkKT7UqVGKD+FSR3zDb8VxjGLnZR2ilqkvk
            acH40YyGGvfgEwwpEQHmoBV/vw8BwfArwirkF9UcDmOycDp4NbkaYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age179l4qmgvh453pk7vy2alqjk8ks7av6kh6g6axmq9n3hk60ytnqvq4s5g7n
    lastmodified: "2026-06-09T21:58:56Z"
    mac: ENC[AES256_GCM,data:Y/jFy5T7I1wk2Pg7rO95Tov+NAHZWVvXzcQR8P16uv8Br66voQzTAFLii5tTcrQSz8zQR3ewDIM2j3bHccpRfNL7zGbVDDRCuA5P6NWS2WxrSO0kLpvGiw2uQTjjaA2GlNns98YL/eUqVJC5GJTE7JG2fZU9EssqjBTgUkZuJnY=,iv:kfrpIB6+aDR/HAn8sz7h+aTEXPq37ygcMzChkeN16/I=,tag:4vA2ESZcVbv/95/gJbzrfw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
